### PR TITLE
Update api.php to fix API documentation

### PR DESCRIPTION
**Pull request by xhorntail**
Fixes the generated output of the API documentation to include an object for the database table.
This allows Swagger generated clients to function properly. ish.

### CODE REVIEW

**Comment by xhorntail** [comment]
Somewhat resolves #306.

**Comment by mevdschee** [comment]
ish?

**Comment by mevdschee** [comment]
I'll test and release a new version soon.

**Comment by xhorntail** [comment]
It works, I'm new to this, but I'd prefer the transform left the table out altogether. This is probably standard though, so I went with 'ish' rather than elaborate on my own ignorance. ;)

**Comment by mevdschee** [comment]
I understand the meaning from your comment on #306. Thank you very much for your contribution!

**Pull request merged**
