### PR TITLE
Update api.php to include charset option

### PR DESCRIPTION
**Pull request by leancode**
In order to be able to connect to a mysql instance I had to change all instances of utf8mb4 to utf8. I just dies with a 9999 error without any hint as to why. As soon as I changed it to utf8 it worked for my database. So I figured there should be a way to override it so it is not set in stone. This is what this commit does.

### CODE REVIEW

**Comment by mevdschee** [comment]
>In order to be able to connect to a mysql instance I had to change all instances of utf8mb4 to utf8

What kind of mysql instance? MySQL or MariaDB and what version number?

**Comment by mevdschee** [comment]
>MySQL 5.5.3 (released in early 2010) introduced a new encoding called utf8mb4 - [source](https://mathiasbynens.be/notes/mysql-utf8mb4)

It seems that

**Comment by leancode** [comment]
OK, let me give you some more data to see if we can shed some light on this: I have some mysql servers v5.0.45-community-nt that run on windows servers that are completely shielded from the world (please don't question why this version and why on windows - beyond my control). I am using your app on an exposed linux box to connect to the mysql's on the internal network to create an api gateway to the world. When I try to connect to the mysql machines the script throws a 9999 error unless I change the parameter to utf8. I am using Navicat to connect to the mysqls from the internal network and Navicat connects perfectly with them. The database in question has the Character Set utf8 and a collation of utf8_general_ci. I also tried with another that was left at default of Swedish etc and it also did not allow to connect with utf8mb4 but only with utf8. Hence my pull request. I think it's generally a good idea to make the character set configurable. And I agree that utf8mb4 is perfect as a default. I am using it whenever I can.

**Comment by mevdschee** [comment]
> I think it's generally a good idea to make the character set configurable.

Well if you communicate with JSON, then by definition it must be UTF8 and in MySQL utf8mb4 is the only correct UTF8 implementation.

**Comment by mevdschee** [comment]
>Changes in MySQL 5.0.96 (2012-03-21)
>End of Product Lifecycle. Active development for MySQL Database Server version 5.0 has ended.

[source](https://downloads.mysql.com/docs/mysql-5.0-relnotes-en.a4.pdf)

As you can see the 5.0 version is declared end-of-life by MySQL more than 8 years ago.

The version you run is unsupported by this software, as only MySQL version 5.6 and up are supported (see README).

I'm not merging as only UTF8 is supported by JSON and I feel it is a bad idea to introduce lossy character set conversions (as I feel it may cause many support issues). 

I'm strongly advising you to upgrade your MySQL and convert the database to utf8mb4.

Feel free to patch or fork my code in any way you like.

**Comment by leancode** [comment]
OK, point taken, no problem. Nothing I can do about my setup unfortunately but I can get it to work with my patches. Well I leave them around, one thing that would be good through would be some sort of better error output. It took me quite a bit to suspect the character set. There is nothing in the logs, no error or debug output. Just thinking out loud....

**Comment by mevdschee** [comment]
If you use the `'debug'=>true` config option, then you should see an error message that helps you a bit, does it?

**Pull request closed without merging**
