### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by hugovoerman**
Stripped it for use with MSSQL only
and made is 'sort of'  schema aware.
It works for GET's, other stuff (update, delete, insert) has not been tested yet!

### CODE REVIEW

**Comment by hugovoerman** [comment]
Hopefully this will 'inspire' and help you to make it schema aware.

**Comment by mevdschee** [comment]
First of all I want to thank you for your contribution. I'm sorry to tell you that your PR is not really "usable" as your proposed changes cannot be reviewed (see: https://help.github.com/articles/using-pull-requests/). This is due to the excessive amount of changed lines (did you reformat the code?).

**Comment by hugovoerman** [comment]
Hi Mauritz,

Yes i reformatted the code using: http://beta.phpformatter.com/
All the red curly lines in WebMatrix were sitting in the way to concentrate on the code.

Meanwhile the code has changed a lot more. I made a new class for AzureSQL, but had to make changes in the base class too. I also changed it, since AzureSQL does not support multiple databases in a server instance. So, perhaps for now, I keep it separate and when a bit more finished put it on github for others to play with and perhaps someone will make it mergeable for you again.

Currently I’m building a generic AngularJS/Bootstrap CRUD application on top of the API. Do you know (perhaps) of any good samples for this? Right now I use https://github.com/szalek/AngularJS-CRUDirective/tree/master/public as a guideline. Perhaps you know of a better one?

Keep up the work with the API please. It really inspired me into bringing this to AzureSQL. Building a genereic fully metadata driven API is a great concept.

Regards,
Hugo

**Comment by mevdschee** [comment]
Thank you for your kind words. I will try to keep up the effort.

**Pull request closed without merging**
