### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by jrock2004**
Wanted to take a shot at implementing authentication. If you are interested I can comment some more of the code changes and write some unit tests if you like

### CODE REVIEW

**Comment by mevdschee** [comment]
Wow.. thank you! I will review it this weekend.

**Comment by jrock2004** [comment]
For the token creation, used the code from this site -> http://tqdev.com/2016-jwt-implementation-in-php

**Comment by mevdschee** [comment]
I have two questions so far:

1. Why is there a special call to retrieve a token? Maybe login should be done using a preflight (options) request?
2. Why use a cookie? Maybe people want to provide the token in the header or as a get parameter.

I need much more time as this is a big effort and needs some serious reviewing. I will merge it this weekend, promised!

**Comment by jrock2004** [comment]
Thanks for the questions. We needed an endpoint that a user can call in which they pass in a username and password so that they can be authenticated, then the API generates them a token, and returns it to them. As far as a cookie, that is a good point. I guess I should not assume that the user would want that short lived token in a cookie. The reason behind the cookie, was it was an easy way for me to not have to generate the token every time. I guess what I should be doing, is storing a session variable with the details and then validating against that.

Yes please review this and if you want me to do something differently, I can. Just trying to help

**Comment by jrock2004** [comment]
So, I was thinking about it and decided to have both options. So by default we will use sessions and keep things server side. Or in the config, a user can switch to cookies if they so desire. Will step back for now and let you code review this

**Comment by jrock2004** [comment]
Anything I need to change or add?

**Comment by mevdschee** [comment]
I used a lot of your code, but restructured it into a separate class. I hope this does not upset you.

**Comment by jrock2004** [comment]
No, I thought about doing that. Just glad to help the project. Will review
what you did to learn.

**Comment by mevdschee** [comment]
Thank you for your effort and your kind words. Please try this new version out and see whether or not it works for you. I'm looking forward to your feedback!

**Comment by jrock2004** [comment]
Will look the code over. First thing I noticed was you got rid of separate config file. Why? I think it would be easy for someone to setup project if you had a configuration file. Would it not?

**Comment by mevdschee** [comment]
I guess it is a matter of taste. The comments in the bottom of the file more or less make up the configuration. You may copy that out to a "config" file and "require" the "api.php" file from that file.

**Comment by jrock2004** [comment]
What happen to the code that I could call and API endpoint to get a token?

**Comment by mevdschee** [comment]
You can still call the api to get a token, check out the "login_token.php" example. The path that it responds to is configurable, so is the verb. It defaults to a "POST" on the empty path "".

**Comment by jrock2004** [comment]
OK, so where in there API.php file are you storing the acceptable username and passwords? Is that at the bottom in the commented out section?

**Comment by mevdschee** [comment]
yes.. in the "authenticator" function/callback, but I guess that you typically want to contact some database and apply a hash function there.

**Comment by jrock2004** [comment]
So I would call the API like this as POST?

```
http://my host/api.php
```

Then what would my post json be?

```
{
   user: admin,
   pass:admin
}
```

**Comment by mevdschee** [comment]
Yes, either form post or json body. Note that the field names are "username", "password" and "token". Also these names are configurable.

**Comment by jrock2004** [comment]
So I just tried and the code is broken. I am getting fatal error ` Fatal error: Call to undefined function PHP_API_AUTH() in C:\Development\php-crud-api\api.php on line 2086`. Should I open an issue to further these discussions?

**Pull request merged**
