### PR TITLE
Allow authorization handler to disable openapi

### LINKED ISSUE #672: Allow authorization handler to disable openapi
See: #671

### PR DESCRIPTION
**Pull request by florianorben**
Adds a new authorization middleware config option:

    'authorization.allowOpenApiAccessHandler' => function () {
        return false;
    },

Returning false from this operation will disable the OpenAPI endpoint

Fixes #672

### CODE REVIEW

**Comment by mevdschee** [comment]
Thank you very much for this contribution. Maybe we can reuse this new handler for other paths ('records', 'columns', etc) as well?

If we call it 'pathHandler' instead of 'allowOpenApiAccessHandler', would you oppose that?

**Comment by florianorben** [comment]
Hey again :)
Nah actually `pathHandler` sounds way better to me ;) and reusing it for the other handlers sounds like a great addition!

Will update this PR tomorrow, since it's pretty late here already :)

**Comment by mevdschee** [comment]
Thank you very much! I really appreciate your effort.

**Review by mevdschee — APPROVED** [review]
Well done!

**Comment by florianorben** [comment]
`allowOpenApiAccessHandler` is now renamed to `pathHandler`.
The callback function in `authorization.pathHandler` will return the current path as an argument now.
Really way more useful this way :)

**Comment by mevdschee** [comment]
> Really way more useful this way :)

Yeah, well done! Great collaboration, thank you.

**Pull request merged**
