### PR TITLE
Ability to have several public keys for JWT signature checking

### PR DESCRIPTION
**Pull request by sebj54**
Here it is, as discussed in #540 :)

I see what you meant, the commented type in the function declaration is not pretty.
Tell me what you think of it, I'll do the docs before the merge.

### CODE REVIEW

**Comment by mevdschee** [comment]
> the commented type in the function declaration is not pretty.

Yeah indeed, that is what I meant. I'm not sure how we should solve this.

**Comment by sebj54** [comment]
I'm not sure either, I looked for solutions in PHP's documentation but didn't find anything about mixed types. I presume it is a bad pattern 😁 

The best solution I see is this one:

1. Move the token deconstruction (string to array) in `getClaims` method.
2. Get the `kid` in `getClaims` too
3. Get the secret from property in that method too (and if it is an array, grab the correct key with `kid`)
4. Pass the `secret` to `getVerifiedClaims` as a string, no matter if it is an array in the configuration

Plus, there is already this check in `getClaims`, which is also in `getVerififedClaims`:

```php
if (!$secret) {
     return array();
}
```

Like this, we can get rid of the token deconstruction and early checks in `getVerifiedClaims`. We can even add a new method to get the secret from the array.

**Comment by sebj54** [comment]
Hi @mevdschee, I just pushed the updated code. 
Tell me if it needs other improvements before merging!

**Comment by mevdschee** [comment]
Looks good to me.. I'll merge it soon and do a major version bump as I feel we may need to break BC in the middleware.. Thank you for your work!

**Comment by sebj54** [comment]
You're welcome! 

The version bump sounds good to me as I changed a function signature.

**Comment by mevdschee** [comment]
Can you review/test the changes?

**Comment by sebj54** [comment]
What is the format of `jwtAuth.secrets`? I tested it with an array, but it does not work.

```
<b>Warning</b>:  explode() expects parameter 2 to be string, array given in <b>C:\wamp64\www\energy-bank-api\vendor\mevdschee\php-crud-api\src\Tqdev\PhpCrudApi\Middleware\Base\Middleware.php</b> on line <b>27</b><br />
<br />
<b>Warning</b>:  array_map(): Expected parameter 2 to be an array, null given in <b>C:\wamp64\www\energy-bank-api\vendor\mevdschee\php-crud-api\src\Tqdev\PhpCrudApi\Middleware\Base\Middleware.php</b> on line <b>27</b><br />
<br />
<b>Warning</b>:  array_filter() expects parameter 1 to be array, null given in <b>C:\wamp64\www\energy-bank-api\vendor\mevdschee\php-crud-api\src\Tqdev\PhpCrudApi\Middleware\Base\Middleware.php</b> on line <b>27</b><br />
<br />
```

You should read "on line 24" and not 27 because I added some debug info:

```php
var_dump($key);
// → string(7) "secrets"

var_dump($default);
// → string(0) ""

var_dump($this->getProperty($key, $default));
/* → array(2) {
["c842..."]=>
string(1139) "-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
"
["5486..."]=>
string(1139) "-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
" */
}

**Comment by mevdschee** [comment]
Thank you for your feedback

**Pull request closed without merging**
