### PR TITLE
after_create

### PR DESCRIPTION
**Pull request by VyseExhale**
Hi Maurits,

I needed a callback function that got triggered on a new db entry (Create).

For example I wanted to send an e-mail to a newly registered member.
In this example I have a "members" table with the columns: id , firstName, lastName, email
the yourEmailFunction method will send a welcome message to the newly entered member.

```php
$api = new PHP_CRUD_API(array(
   /* 
    ......
     all other settings 
    */
   'after_create'=>function($db,$tab,$row) {
      if ($tab == 'members') 
         yourEmailFunction($row['firstName'],$row['lastName'],$row['email']);
      }
   }
));
$api->executeCommand();
```
Tell me you thoughts... maybe if you like it and willing to accept the pull request I could also create an after_delete and after_update method.

### CODE REVIEW

**Comment by mevdschee** [comment]
Can we modify the handler so that it gets called on 'create', 'update' and 'delete'? And name it different.. something like.. 'after_write' or so..

**Comment by mevdschee** [comment]
It now supports all operations and there multi-record versions and also takes transactions into account. It allows you to define a callback that has the following arguments:

- $action
- $database
- $table
- $id
- $input
- $output

when the action is a 'read' or a 'list' the output is not specified (due to the streaming nature of the api).

**Comment by VyseExhale** [comment]
Haha got inspired? :) very nice!

**Comment by mevdschee** [comment]
Yes I did. I hope it still supports your use case. I'm considering adding a "before" handler as well, but I'm not sure about the use cases yet.

**Comment by VyseExhale** [comment]
Yes it does still supports it!

And a before handler could be handy on update. For exampje if you need to know what exactely had changed to the content.. you can set a global var with before values and in the after create you can compare those values with the new data.

**Pull request merged**
