### PR TITLE
Bug in beforehandler, on deleting multiple rows

### PR DESCRIPTION
**Pull request by VyseExhale**
Hi there,

We're allmost there, I found 2 bugs, one I solved with this pull request:

The first one: on deleting multiple rows at once and applying my soft delete [see example 209](https://github.com/mevdschee/php-crud-api/issues/209) I got an 404 errror : Subject caused by the [updateObject method](https://github.com/mevdschee/php-crud-api/blob/master/api.php#L1533-L1535) 

The other you will find here [209](https://github.com/mevdschee/php-crud-api/issues/209), this needs to be discussed first.

### CODE REVIEW

**Comment by mevdschee** [comment]
Can you verify that the "deleting multiple rows issue" still exists in v1.0.9?

**Comment by VyseExhale** [comment]
Nope it still throws "Not found (subject) " since the $inputs holds only 1 object.. and need multiple on a multiple deletion

**Comment by mevdschee** [comment]
Ah.. I get it.. so you should really modify inputs so that it holds multiple values.

```
$inputs = array_map(function($v){return array('deleted'=>date('Y-m-d H:i:s', time());},$ids);
```

Something like that?

**Comment by VyseExhale** [comment]
I mean: 

when you do 
```
DELETE http://localhost/api.php/categories/1,2
```

In the current situation 
```php
'before'=>function(&$cmd, &$db, &$tab, &$id, &$in) {  }
```
$id = '1,2'; and the $in parameter holds an array with ONE object.

which shoud be 2 objects.. one for $id 1 and one for $id 2..

since in the [updateObject method](https://github.com/mevdschee/php-crud-api/blob/master/api.php#L1533-L1535)  you check the $inputs count agains the multiple count.. 
```
(count($inputs)!=count($keys)
```
Which in the current situation would evaluate to (1!-2)

**Comment by mevdschee** [comment]
So, shouldn't we just change the example?

**Comment by VyseExhale** [comment]
... uhhhhh .. .well ... not really sure..

first off, I think the functionality for the end user should be as "easy to use" as possible...  now the end user has to do something that feels complex in my opinion.

Second.. on a multiple deletion the $in param has one object.. which has no use at all.. so it either holds 2 values (on 2 deletions), or null., since you can't do anything with it.


Also I found another bug  [this foreach](https://github.com/mevdschee/php-crud-api/blob/master/api.php#L1883-L1892) wil overwrite the inputs returned by applyBeforeHandler

**Comment by VyseExhale** [comment]
Makes me think, wouldn't it  be better .. if on a multiple Update .. for example 
```php
PUT http://localhost/api.php/categories/1,2
[{"name":"Internet"},{"name":"Programming"}]
```
the "before" => function() { ... } would get called twice

first time 
```php
'before'=>function(&$cmd, &$db, &$tab, &$id, &$in) {  
$id; // 1
$in; //{"name":"Internet"}
}
```

second time
first time 
```php
'before'=>function(&$cmd, &$db, &$tab, &$id, &$in) {  
$id; // 2
$in; //{"name":"Programming"}
}
```

**Comment by mevdschee** [comment]
I agree, I was doubting whether or not that would be a good idea, maybe it is indeed..

**Comment by VyseExhale** [comment]
I think it is! And maybe this would also be better for the after callback.. .

**Comment by VyseExhale** [comment]
[like this?](https://github.com/mevdschee/php-crud-api/pull/210/commits/68a4043965e2cefe08711a046620d510b9a70f0c);

**Comment by mevdschee** [comment]
Thank you. I did some refactoring in 919e820ba0e02eb083da90d34dcc4dd2a4a138f0

**Comment by mevdschee** [comment]
Can you verify that the issue is gone in v1.1.3?

**Comment by VyseExhale** [comment]
No it's not, see #212

**Pull request merged**
