### PR TITLE
Updated/enhanced functionality:

### PR DESCRIPTION
**Pull request by ShamimIslam**
Mutli-column filters with functions w/o [] notation
Multiple oder by clauses
'op' operation to allow debugging

### CODE REVIEW

**Comment by mevdschee** [comment]
Thank you for your contribution, but I can't merge this, because:

- Pull requests should be made for individual features 
- Pull requests should include tests if they introduce new features.

As for the changes, I'm do not merge any new feature (it must be upvoted)

- 'op' operation to allow debugging already exists, it is called 'method' in the configuration.
- I don't see the need for "Mutli-column filters with functions w/o [] notation"
- Your "Multiple order by clauses" implementation is highly insecure and I don't see the need either.

Feel free to fork, the code is MIT licensed.

**Comment by ShamimIslam** [comment]
I added the features because it is what I needed as the current software did not meet my needs. Especially the assumption that only one column could have an order by was very limiting. Also, having to use the '[]' notation made it difficult and confusing to use in JavaScript. I used the ||| in the filter to inject the same behavior your code had without relying on PHP's array feature. 

Personally, I liked how you handled the code, but I was concerned that you had re-assigned features of the HTTP protocol to SQL operations but the assumption was very arbitrary. It would have been EASIER and more straightforward and caused less of a learning curve if you had just used the SQL crud operators instead of subverting HTTP. And I was concerned about how complex the dataset became because you had housed the SQL interface in HTTP - had you mapped it to the SQL CRUD operations, it would have been much easier to determine which parameters were required and you would have had a simpler uniform input interface.

Rather than rewrite the code to use the SQL operators, I only extended what you had so that your existing tests could still be applied to ensure nothing had been broken. 

If you note, the "op" operation injects the data "as-if" the original request had been a PUT or a POST.

The order simply assumes there is more than one column possible.

The filter simply uses a different notation in the string for the split.

You have a great idea. I was only trying to assist and give back.

If you don't want it, I'm happy to fork and make the major changes I've described and add back on the SQL operations. As stated by Dr Alexander Lamb back in the 70's and 80s who was also my teacher at one time, software should have a primary secret. SQL operations are the secret. 

We should not be hiding them in another secret when that additional software is only a conduit.

**Comment by ShamimIslam** [comment]
P.S. Looks like you had another commit after I pulled your code as there is a section listed as changed that I did not affect. All my changes have comments and are limited to the filter, the op and the order. Any other changes should be ignored. I did not add them.

**Comment by mevdschee** [comment]
@ShamimIslam FYI, feature req #162 was implemented.

**Pull request closed without merging**
