### PR TITLE
Add custom endpoints

### PR DESCRIPTION
**Pull request by sebj54**
Hi there, me again :grin:

I find your project very flexible but I missed just one feature: custom endpoints.

I made a very few changes to allow the adding of custom endpoints very easily. It can be done by following a few simple steps.

First, create a controller for your endpoint, like this one:

```php
<?php

namespace MyNamespace; // optional

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Tqdev\PhpCrudApi\Controller\CustomController;
use Tqdev\PhpCrudApi\Middleware\Router\Router;


class MyCustomController extends CustomController
{
    protected function registerRoutes(Router $router)
    {
        $router->register('POST', '/custom/endpoint', [$this, 'customEndpoint']);
    }

    public function customEndpoint(ServerRequestInterface $request): ResponseInterface
    {
        // Insert logic for this endpoint

        return $this->responder->success(1);
    }
}
```

The most important for this controller is that it should extends `CustomController`. 

Then, the only thing left is to register this controller in the config:

```php
$config = new Config([
    'username' => 'xxx',
    'password' => 'xxx',
    'database' => 'xxx',
    'controllers' => 'records,openapi,custom:\\MyNamespace\\MyCustomController ',
]);
```

Tell me what you think!

### CODE REVIEW

**Comment by mevdschee** [comment]
Can we somehow support openapi specification for custom endpoints?

**Comment by sebj54** [comment]
That is a good question, I have actually no knowledge at all about openapi. I assume it describes every API route, especially parameters, right?

You're right about the dedicated config parameter, I will update that!

**Comment by mevdschee** [comment]
@sebj54 I would be very thankful if you would review/test the changes.

**Comment by mevdschee** [comment]
I added `customOpenApiBuilders` as a config parameter.

**Comment by sebj54** [comment]
I confirm it works! Did not test the `customOpenApiBuilders`though.

Sorry for the late response, I spent a few hours trying to debug the issue I just posted (https://github.com/mevdschee/php-crud-api/issues/573). I thought the "Route not found" error was related to the custom endpoints… 🤦‍♂

**Pull request closed without merging**
