### PR TITLE
default types validation

### PR DESCRIPTION
**Pull request by lcuis**
See details here:
https://github.com/mevdschee/php-crud-api/issues/592

Adapted:
- the validation middleware
- the readme
- the tests
- some details in the docker related files

### CODE REVIEW

**Comment by mevdschee** [comment]
Thank you!

**Comment by mevdschee** [comment]
@lcuis Please check the comments on the above commit. It explains what I have changed.

**Comment by lcuis** [comment]
Thanks for your comments and adaptations. I’ll try to test as soon as possible. Probably tomorrow.

**Comment by mevdschee** [comment]
Feel free to add more test cases when you find problems.

**Pull request merged**
