### PR TITLE
1st attempt at adding exclude= (issue #136) try#2

### PR DESCRIPTION
**Pull request by jr3cermak**
Feel free to change the behavior if this is undesired. This adds the exclude= parameter. I added a few tests to demonstrate the behavior. If both include and exclude are present, then include is run first pulling in any relations and then exclude is run. If there are multiple tables in the return, the exclude parameter must be in the format {table}.{column/field}. If there is a single table in the return, the exclude parameter may just be {column/field}. This could be improved to exclude entire tables, say {table}.*?. Some exclusions have unintended behavior. For example, if you change the test from &exclude=comments.message to &exclude=category.id, it will drop all the fields from category instead of just removing category.id. Otherwise, it works for general cases. (This includes a test suite change for a commit that included improved CSRF handling commit bef88a9c8bfb8357e169bcd43a92127ad860bea0).   The test suite passes for at least sqlite.

### CODE REVIEW

**Comment by mevdschee** [comment]
This is very well done! I love it and after testing it tonight I will merge it.

**Comment by mevdschee** [comment]
I am happy with the current implementation and your tests still succeed. All that is left is to add documentation to complete the implementation.

**Comment by mevdschee** [comment]
Done. Thank you very much!

**Comment by maoamid** [comment]
when I tested today the exclude parameter it worked fine except that the excluded columns name still appear in the 'columns' array list. Is that the expected result?

**Comment by maoamid** [comment]
My mistake, it seems I messed up with params in testing, I confirm it's working fine.
Great work,

**Pull request merged**
