### PR TITLE
Update api.php

### PR DESCRIPTION
**Pull request by juanpex**
Solve "You have an error in your SQL syntax" error with empty selectColumns variable.

### CODE REVIEW

**Comment by mevdschee** [comment]
Hi @juanpex, thank you for your contribution. Why would it default to '*' and not to '0'? When do you run into this issue? Kind regards, Maurits

**Comment by juanpex** [comment]
I'm connecting to a mysql database on remote server. The database user has some restrictions, is not managed by me.
All the tables except one has a problem "setting that columns variable". I don't know why but this is the full message error:


`{
    "code": 9999,
    "message": "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM \"clientes\"' at line 1"
}`

**Comment by juanpex** [comment]
ok, "clientes" is not a table, is a view.

**Comment by mevdschee** [comment]
>I don't know why but this is the full message error:

Can you also share the full URL that is requested? Maybe I can reproduce that error.

**Comment by apdug** [comment]
> > I don't know why but this is the full message error:
> 
> Can you also share the full URL that is requested? Maybe I can reproduce that error.

Sorry I can't give you access to the api. That database is't my.

**Comment by juanpex** [comment]
> > I don't know why but this is the full message error:
> 
> Can you also share the full URL that is requested? Maybe I can reproduce that error.

Sorry I can't give you access to the api. That database is't my.

**Comment by mevdschee** [comment]
>Sorry I can't give you access to the api. That database is't my.

I only need what put behind 'api.php', not what you put before that. Can you share that?

**Comment by juanpex** [comment]
> > Sorry I can't give you access to the api. That database is't my.
> 
> I only need what put behind 'api.php', not what you put before that. Can you share that?

You need this?

http://domain/api.php/records/clientes

**Comment by mevdschee** [comment]
I'm sorry but I can't reproduce this issue. If you open an issue first then we can work out reproduction steps. If the issue is reproduced you can refer to this (closed) PR as a fix.

**Pull request closed without merging**
